### ISSUE TITLE
Unable to deploy with cloudformation

### ISSUE THREAD

**Issue by MatteoGioioso** [localstack/awscli-local#28]
I am trying to deploy a SAM template using cloudformation, the packaging seems to work fine, however when I try to deploy it just returns `'Parameters'` 

this is the script I am using:

```

awslocal s3 mb s3://${BUCKET}

awslocal \
  --s3-endpoint-url=http://localhost:4566 \
    cloudformation package \
    --template-file template-local.yaml \
    --output-template-file output.yaml \
    --s3-bucket "${BUCKET}"

awslocal cloudformation deploy \
  --template-file output.yaml \
  --stack-name "${PROJECT}" \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides \
  Environment="${ENV}" \
  Appname="${APPNAME}"

```

Docker-compose:

```
version: "3"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=s3,lambda,apigateway,cloudformation,iam
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - '4572:4572'
      - '4566:4566'

```

this is the output of the script:

```
make_bucket: connections-test-dev-lambda-deployment-artifacts
Uploading to 9b170e29aed89b91edbf6e8c18ef4aa6  9151213 / 9151213.0  (100.00%)
Successfully packaged artifacts and wrote output template to file output.yaml.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file /Users/path/to/template/output.yaml --stack-name <YOUR STACK NAME>

'Parameters'

```

The same script works fine if I deploy on AWS

I have also tried this:

```

aws --endpoint-url=http://localhost:4566 --profile ${PROFILE} --region ${REGION} cloudformation deploy \
  --template-file output.yaml \
  --stack-name "${PROJECT}" \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides \
  Environment="${ENV}" \
  Appname="${APPNAME}"

```
But I get the exact same output

Versions:

```
localstack: 0.12.2
awslocal: aws-cli/1.18.181 Python/3.9.0 Darwin/19.6.0 botocore/1.19.21

```

Any help is appreciated. Thanks.

## Some more informations:

Localstack start-up output logs:

```

Waiting for all LocalStack services to be ready
2020-11-19 01:38:20,012 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-11-19 01:38:20,018 INFO supervisord started with pid 13
2020-11-19 01:38:21,027 INFO spawned: 'dashboard' with pid 19
2020-11-19 01:38:21,039 INFO spawned: 'infra' with pid 20
2020-11-19 01:38:21,060 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-11-19 01:38:21,066 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
LocalStack version: 0.12.2
2020-11-19 01:38:22,867 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock API Gateway service on http port 4566 ...
[2020-11-19 01:38:32 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2020-11-19T01:38:32:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2020-11-19 01:38:32 +0000] [21] [INFO] Running on http://0.0.0.0:39947 (CTRL + C to quit)
2020-11-19T01:38:32:INFO:hypercorn.error: Running on http://0.0.0.0:39947 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Starting mock CloudFormation service on http port 4566 ...
Starting mock CloudWatch service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
ERROR: 'docker ps -a --filter="name=localstack_lambda_*" --format "{{.Names}}"': exit code 1; output: b''
Starting mock S3 service on http port 4566 ...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Ready.


```

**Comment by MatteoGioioso** [comment]
This seems to happen when the stack is in `CREATE_FAILED` state. 
In reality the error I got different, I think I will open another issue.

```

2020-11-19T02:06:23:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f0c2e145ca0>(None) failed: MyHTTPConnectionPool(host='436fb142c9c4', port=58901): Max retries exceeded with url: /2015-03-31/functions/connections-test-dev-lambda-171bbb7a (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0c2e136f10>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

```

2020-11-19T02:11:30:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed:
b'' Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 452, in _parse_xml_string_to_dom
    root = parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

I will leave this open, in my opinion it should show something more meaningful.

**Comment by whummer** [comment]
Thanks for reporting @MatteoGioioso .

Can you please share the contents of the CloudFormation template file?

Looking at the error message below - it seems that the Docker daemon cannot be access from within LocalStack. 
```
ERROR: 'docker ps -a --filter="name=localstack_lambda_*" --format "{{.Names}}"': exit code 1; output: b''
```

Please note that Docker access is required to run Lambda functions. Can you please ensure that the docker socket is mounted as a volume - like in the sample config here: https://github.com/localstack/localstack/blob/master/docker-compose.yml
```
volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by MatteoGioioso** [comment]
Hello @whummer thanks for the suggestion, but for the time being I gave up on this. I should have closed this issue!
Sorry for the inconvenience!

**Comment by paul-uz** [comment]
@MatteoGioioso how did you get `--s3-endpoint-url` to work with `awslocal` ? I get the error "Unknown options: --s3-endpoint-url=http://localhost:4566,--s3-endpoint-url=http://localhost:4566"
