### ISSUE TITLE
bug: cannot install for python 3.7.4

### ISSUE THREAD

**Issue by WilhelmStein** [localstack/awscli-local#56]
### Specs

OS: ManjaroLinux
Version: 21.2.6
PythonVersion: 3.7.4
PipVersion: 22.1

### Description
I tried installing the `awscli-local` package using pip, but I get the following output:

```
Collecting awscli-local[ver1]
  Using cached awscli-local-0.20.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-gl3b465n/awscli_local.egg-info
      writing /tmp/pip-pip-egg-info-gl3b465n/awscli_local.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-gl3b465n/awscli_local.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-gl3b465n/awscli_local.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-gl3b465n/awscli_local.egg-info/top_level.txt
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8v6hjaq1/awscli-local_2e45f7fad4a54eb7bc89219706a3cc40/setup.py", line 46, in <module>
          "Topic :: Software Development :: Testing"
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 300, in run
          writer = ep.load()
        File "/home/phii/Code/aws-test/.venv/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: module 'plugin.setuptools' has no attribute 'load_plux_entrypoints'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by yo-ga** [comment]
@WilhelmStein  Maybe you can try the following:
1.  Run the pip install command with the `--use-deprecated` option.
2. Upgrade `setuptools` package

**Comment by lakkeger** [comment]
Hi! We just wanted to follow up to see whether your issue has been resolved. Were you able to get it working with the latest version? We would appreciate your feedback!

**Comment by lakkeger** [comment]
Closing issue due to inactivity.
